
import { Inter } from "next/font/google";
import "./globals.css";
// import { SiteHeader } from "@/components/Nav/site-header";
import Footer from "@/components/footer";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  manifest: "/manifest.json",
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={inter.className}>
              {/* <SiteHeader /> */}
              {children}  
            <Footer />
        </body>
      </ClerkProvider>
    </html>
  );
}
